language: cpp
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -q
install:
 - sudo ./prepare-release travis-ci
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-4.8
 - export CXX=g++-4.8
script: make && make test && test/integration/run-tests
